// ── HELPERS ──────────────────────────────────
const M   = (v,l,s,ft,sub) => ({t:'m',v,l,s:s||null,ft:!!ft,sub:sub||null});
const ST  = h          => ({t:'s',h});
const SEC = title      => ({t:'sec',title});

// ── DATA ─────────────────────────────────────
const YEARS = [
{
  id:'2017', label:'Año 1', period:'Abr 2017 — Abr 2018', color:'#f5c842',
  stats:[
    M('1.992','personas que leen',null,true),
    M('61.09%','tasa de apertura'),
    M('82','personas se desuscribieron este año'),
    M('36.977','correos enviados','21.089 fueron abiertos.'),
    M('149','suscripciones en una semana','Luego de <a href="https://comofuncionanlascos.as/mirar-por-la-ventana-del-colectivo-f652873f06e6"><em>Cómo funciona mirar por la ventana del colectivo</em></a> — también el correo con más desuscripciones del año (10).',true),
    M('175','temas sugeridos','<a href="https://comofuncionanlascos.as/sugerencias-e93b7d446a18">Ver todos</a>. "Cómo funciona viajar por el mundo" es el más pedido que aún no escribí.'),
    M('1','vez marcaron spam','Y un poco me molestó porque nadie la obligó a suscribirse. Ay, estos humanos.'),
    M('349','conversaciones','Con 7 personas que leen en promedio por cada una.'),
    M('20','respuestas tuvo el correo más respondido','<a href="https://comofuncionanlascos.as/abrazos-b2e47734b0ef"><em>Cómo funcionan los abrazos</em></a>. Le siguió <a href="https://comofuncionanlascos.as/hacer-amigos-efb9d9dfb95"><em>Cómo funciona hacer amigos</em></a> con 19.'),
    M('22','recomendaciones en Medium','Promedio por correo.'),
    M('2','libros regalados','De <a href="http://publicaciones.filo.uba.ar/filosof%C3%ADa-y-cultura-popular">Filosofía y Cultura Popular</a>, a personas que leen.'),
    M('5','cafés compartidos con personas que leen'),
  ]
},
{
  id:'2018', label:'Año 2', period:'Abr 2018 — Abr 2019', color:'#f0a030',
  stats:[
    M('4.957','personas que leen','Casi 5 veces más que hace un año.',true),
    M('59.18%','tasa de apertura','Casi 2% menos que hace un año.'),
    M('458','personas se desuscribieron este año'),
    M('1.044','removidos por inactividad','Sin esto, la lista rozaría los 6.000 suscriptores.'),
    M('85','personas se sumaron cada semana, en promedio'),
    M('9','personas se desuscribieron por semana','En promedio.'),
    M('254','suscripciones en una semana','Luego de <em>Algunas torpes palabras sobre algunas cosas III</em>.',true),
    M('25','desuscripciones en una semana — récord del año','Luego de <a href="https://comofuncionanlascos.as/querida-persona-que-lee-2018-ad670d58f7e5"><em>El hombre de los nombres</em></a>.'),
    M('443','temas sugeridos','268 este año. "Cómo funciona viajar por el mundo" sigue siendo el más pedido.'),
    M('155.804','correos enviados','91.081 abiertos.'),
    M('673','conversaciones','14 por correo en promedio.'),
    M('100%','tasa de respuesta','Aunque a veces me tome algunos días.'),
    M('63','respuestas al correo de fin de año','Más que triplicando el récord anterior.'),
    M('17','recomendaciones en Medium','5 menos que el año anterior.'),
    M('1','newsletter que surgió de mis correos','El de <a href="http://guadalupemuro.com/">mi hermana Guadalupe</a>.'),
    M('3','propuestas serias para un libro','Y muchas otras muy poco serias.'),
    M('3','botellas de Johnnie Walker Black','Tomadas escribiendo el newsletter en el último año.'),
    ST('Cuando <a href="https://medium.com/@valenzine/bonk-935870ae12d8">escribí sobre el orgasmo femenino</a> una persona se borró ofendida de que haya dicho que Freud era un chanta.'),
    ST('Una vez más, casi todos los correos fueron escritos bajo el influjo de café, whisky o Chardonnay, escuchando <a href="https://open.spotify.com/album/2jStuYeaRty1cwxjoxfo9K"><em>Lovely Little Lonely</em></a> de The Maine o <a href="https://open.spotify.com/album/7AJPV0L05IyIBid97AvwVD"><em>Worlds</em></a> de Porter Robinson, en repeat.'),
    M('711','suscriptores en Telegram','Un 61,59% más que hace un año.'),
    SEC('Club de la curiosidad'),
    M('98','personas en débito automático','Para que yo pueda vivir de escribir.'),
    M('57,1%','son mujeres entre quienes apoyan mi trabajo','42,9% varones.'),
    M('3','semanas pasan en promedio','Entre correo y correo especial para el Club.'),
    M('4','correos del diario de viaje','Enviados al Club durante mi estadía en Bariloche en febrero.'),
    M('117','compras en Book Depository','Con <a href="http://bookdepository.com/?a_aid=valentinmuro&chan=newsletter">mi enlace</a>.'),
    M('65','personas a las que les pregunté su talle de remera','Hasta que me di cuenta de que era una pregunta muy extraña.'),
    SEC('El dinero'),
    M('10.000','pesos donados','A 4 organizaciones que protegen a animales, en honor y memoria de Turing. El dinero vino del <a href="http://club.comofuncionanlascos.as/"><em>Club de fans de la curiosidad</em></a>.'),
  ]
},
{
  id:'2019', label:'Año 3', period:'Abr 2019 — Abr 2020', color:'#e8694a',
  stats:[
    M('9.670','personas que leen','Casi el doble que hace un año.',true),
    M('55.98%','tasa de apertura','Casi 3% menos que el año anterior.'),
    M('984','personas se desuscribieron este año','Casi el doble que el año anterior.'),
    M('2.165','personas consultadas por inactividad','Si querían seguir en la lista.'),
    M('160','personas se sumaron cada semana, en promedio'),
    M('22','personas se desuscribieron por semana','En promedio.'),
    M('1.642','suscripciones en una semana','Luego de <a href="https://comofuncionanlascos.as/seis-grados-de-separacion-a8b2c295cc7d">"Cómo funciona los seis grados de separación"</a> — coincidió con el video de Netflix. Le siguieron <a href="https://comofuncionanlascos.as/preocuparse-8a20a29508a2">"preocuparse"</a> y <a href="https://comofuncionanlascos.as/fuego-5f7c82ded114">"lo que el fuego se llevó"</a>, con 365 nuevas personas cada uno.',true),
    M('43','desuscripciones en una semana — récord del año','Luego de <a href="https://comofuncionanlascos.as/voz-interior-2377ad0303e4">"Cómo funciona nuestra voz en la cabeza"</a>.'),
    M('666','temas sugeridos','398 este año. "Cómo funciona viajar por el mundo" sigue siendo el más pedido.'),
    M('297.811','correos enviados','164.081 abiertos.'),
    M('7','correos de misceláneas','3 de preguntas hechas por niños · 5 reediciones.'),
    M('35 días','fue el máximo que pasé sin enviar correos.'),
    M('100%','tasa de respuesta','Aunque a veces me tome algunos meses.'),
    M('1','episodio del podcast','<a href="https://anchor.fm/algunastorpespalabras"><em>Algunas torpes palabras</em></a>. Uno más grabado pero no publicado aún.'),
    M('17','hechos curiosos','Agregados al final de mis correos para que puedas sonreír.'),
    M('4','botellas de Johnnie Walker Black','Una más que el año pasado.'),
    M('5 hs. 29 min.','pasé analizando números y escribiendo mi resumen anual'),
    ST('Cuando me invitaron a presentarle mis ideas al presidente un montón de personas se desuscribieron porque vieron en eso un sentido que simplemente no tenía.'),
    ST('Varias veces marcaron correos míos como spam, pero dejé de contarlos. Lo lindo de mi lista es que nunca sumé a nadie así que si marcás como spam sos básicamente una persona horrible.'),
    SEC('Las personas que leen'),
    M('94','respuestas recibí a la carta del año anterior','Un 49% más que el récord anterior.'),
    M('998','conversaciones','20 por correo en promedio.'),
    SEC('El dinero'),
    M('USD 1.256,33','invertidos en Mailchimp','Desde julio de 2018, total acumulado.'),
    M('$28.484','pesos donados','A <a href="https://telegra.ph/Donaciones-del-Club-de-la-curiosidad-04-19">13 organizaciones</a>: Fundación Huésped, Médicos Sin Fronteras, Hacé Feliz a un Gato, Bicho Feliz, CEMIC, Casa Manu y otras.'),
    M('250+','libros comprados','Con <a href="http://bookdepository.com/?a_aid=valentinmuro">mi enlace en Book Depository</a>.'),
    M('85','reproducciones de <em>Lovely Little Lonely</em>','De The Maine — el más escuchado mientras escribí. Le siguieron <a href="https://open.spotify.com/album/1fPQaZhs8bWeL3Io9u4TsD?si=r1ldUh4GRfGx8IZmKj_1Tw"><em>You Are OK</em></a> (48), <a href="https://open.spotify.com/album/7AJPV0L05IyIBid97AvwVD"><em>Worlds</em></a> (47) y <a href="https://open.spotify.com/album/4gARZz9eV7zbGbtOjhVTPF"><em>Nine</em></a> de blink-182 (43). <a href="https://www.last.fm/user/valenzine">Más detalles</a>.'),
    M('1.076','suscriptores en Telegram','Un 51,3% más que hace un año.'),
  ]
},
{
  id:'2020', label:'Año 4', period:'Abr 2020 — Abr 2021', color:'#c44d89',
  stats:[
    M('14.032','personas que leen',null,true),
    M('53.13%','tasa de apertura','Promedio de 38 correos enviados.'),
    M('24.609','personas alguna vez recibieron mis correos','3.802 se desuscribieron.'),
    M('10.501','personas se suscribieron este año'),
    M('2.236','personas se desuscribieron este año'),
    M('284','personas se sumaron cada semana, en promedio','Un 77,5% más que el año anterior.'),
    M('59','personas se desuscribieron por semana','Un 168,18% más que el año anterior.'),
    M('4.237','personas consultadas por inactividad','428 decidieron quedarse y seguir leyendo.'),
    M('1.020','suscripciones en una semana','Luego de reenviar <a href="https://comofuncionanlascos.as/papa-noel-747f2aa33e42">"Cómo funciona ser Papá Noel"</a> en julio. Le siguieron <a href="https://comofuncionanlascos.as/aceptar-lo-que-no-podemos-cambiar-5c6877e37b23">"aceptar lo que no podemos cambiar"</a> (961) y <a href="https://comofuncionanlascos.as/paciencia-c520918a0e63">"la paciencia"</a> (832).',true),
    M('83','desuscripciones en una semana — récord histórico','Luego de <a href="https://comofuncionanlascos.as/hacerse-muchas-preguntas-2c8bce926df2">"Cómo funciona hacerse muchas preguntas"</a>, mi charla TEDx.'),
    M('819','temas sugeridos','154 este año. "Cómo funciona viajar por el mundo" sigue siendo el más pedido.'),
    M('38','correos distintos','Enviados este año.'),
    M('28 días','fue el máximo que pasé sin enviar correos.','7 días menos que el año pasado.'),
    M('215 hs. 9 min.','pasé investigando y escribiendo','Los "cómo funciona".'),
    M('111 libros','consulté para escribir este año','Sin artículos registrados. Los que revisé y descarté: imposible llevar la cuenta.'),
    M('11 hs. 18 min.','pasé grabando videos de bienvenida','Para las personas que se sumaron al Club.'),
    M('25 hs. 32 min.','pasé en diseño y redes sociales'),
    M('8 hs. 55 min.','pasé en nomesientobien.com'),
    M('4 hs. 52 min.','pasé analizando números y escribiendo mi resumen anual','<i class="dn">▼</i> 37 min. menos que el año anterior.'),
    ST('En el último año no tuve ninguna reunión con algún primer mandatario.'),
    SEC('Las personas que leen'),
    M('96','respuestas recibí a la carta del año anterior','Un 2,12% más que el año anterior.'),
    M('668','conversaciones','18 por correo en promedio. Un 33% menos que el año anterior.'),
    M('1.434','correos respondidos','356 aún pendientes.'),
    M('35 hs. 58 min.','pasé respondiendo correos','Un 56% menos que el año pasado.'),
    M('341','mensajes de recomendación acumulados','Y cada mensaje es más lindo que el anterior. <a href="https://amor.cflc.email">Leé todos →</a>'),
    M('83','libros comprados con mi enlace','Un 66,8% menos que el año pasado.'),
    M('1.418','suscriptores en Telegram','Un 31,78% más. 378 en canal personal.'),
    M('3','botellas de Johnnie Walker Black','Una menos que el año pasado.'),
    SEC('Club de la curiosidad'),
    M('0','libros escritos','A pesar de mis intentos.'),
    M('162','correos del Club','437 curiosidades · 148 citas · un diario de viaje y todo lo que no me animo a enviarle a nadie más.'),
    M('290 hs. 19 min.','pasé en el Club de la curiosidad','Investigando, traduciendo, recopilando y redactando curiosidades.'),
    ST('Junio y julio fueron los meses con más nuevos apoyos económicos, luego de que renunciara a mi trabajo. No hay un solo día en el que no me parezca increíble tener el mejor trabajo del mundo gracias a las personas que creen en mí.'),
    SEC('El dinero'),
    M('$1.338,28','USD — Mailchimp este año','$2.624,61 total acumulado. La conversión a pesos sería muy deprimente.'),
    M('$115.313','pesos donados','A <a href="https://docs.google.com/spreadsheets/d/1wEtxpbgtjzo8Fc_quprPtwVvCKGcPIpbpyFSVj-hM1Q/edit?usp=sharing">13 organizaciones</a>: Fundación Huésped, Médicos Sin Fronteras, Hacé Feliz a un Gato, Bicho Feliz, Patitas Glew, Estamos Acá, Rodrigo Bueno, Proyecto 4 patas, ACMA y otras.'),
    M('$513.271,08','pesos juntados para el personal médico de Chaco','En dos campañas junto a Julia Bártoli y Eliana Iñiguez.'),
    SEC('Redes sociales'),
    M('8.614','nuevos seguidores en Twitter','Un 47,93% más que el año pasado.'),
    M('8.534','nuevos seguidores en Instagram','Un 75,24% más que el año pasado.'),
  ]
},
{
  id:'2021', label:'Año 5', period:'Abr 2021 — Abr 2022', color:'#9a5fd1',
  stats:[
    M('14.866','personas que leen',null,true),
    M('53.17%','tasa de apertura','Promedio de 28 correos. Apenas 0,03% más alta que el año anterior.'),
    M('30.097','personas alguna vez recibieron mis correos','5.464 se desuscribieron. 9.767 archivadas por inactividad.'),
    M('4.870','personas se suscribieron este año','Casi la mitad que el año anterior.'),
    M('1.422','personas se desuscribieron este año'),
    M('94','personas se sumaron cada semana, en promedio','Un 67% menos que el año anterior.'),
    M('27','personas se desuscribieron por semana','Un 54% menos que el año anterior.'),
    M('1.063','suscripciones en una semana','Luego de <a href="https://comofuncionanlascos.as/28-dias-455534fdb06f">"28 Días"</a> en junio. Le siguieron <a href="https://comofuncionanlascos.as/gracias-e6d6a743d98d">"dar gracias"</a> (446) y <a href="https://comofuncionanlascos.as/paciencia-c520918a0e63">"la paciencia"</a> (321).',true),
    M('80','personas se desuscribieron','Luego de reenviar "Cómo funciona dar gracias".'),
    M('895','temas sugeridos','95 este año. "Cómo funciona viajar por el mundo" sigue siendo el más pedido.'),
    M('28','correos distintos','10 menos que el año anterior.'),
    M('56 días','fue el máximo que pasé sin enviar correos.','Exactamente el doble que el año pasado.'),
    M('325 hs. 54 min.','pasé investigando y escribiendo','Un 41% más que el año anterior. Cada "cómo funciona" tomó en promedio 13 hs. 24 min.'),
    M('125 libros + 74 artículos','consulté para escribir este año','Los que revisé y descarté: imposible llevar la cuenta.'),
    M('19 hs. 22 min.','pasé grabando y editando lecturas'),
    M('9 hs. 4 min.','pasé analizando números y escribiendo mi resumen anual','<i class="up">▲</i> 4 hs. 12 min. más que el año anterior.'),
    M('73 hs. 26 min.','armando los 28 Días','4 hs. 35 min. solo para el final del día 28.'),
    M('659','cartas postales enviadas','A 570 personas del Club. Aprox. un 20% se pierde antes de llegar a destino.'),
    M('47 hs. 41 min.','armando las cartas postales','6 hs. 53 min. sobres · 5 hs. 50 min. direcciones · 4 hs. 30 min. firmando · el resto preparando para llevar al correo.'),
    M('10 hs. 22 min.','ordenando todos mis correos','+ 48 hs. 23 min. programando el <a href="https://museo.curiosidad.club/"><em>Museo de Cómo funcionan las cosas</em></a>.'),
    M('6 hs. 20 min.','armando esta carta','2 hs. 54 min. en los números + 3 hs. 25 min. escribiendo.'),
    ST('Desde octubre hasta enero, por primera vez, cada mes el Club se fue achicando y tuve un poco de miedo, pero en febrero comenzó a crecer otra vez. No hay un solo día en el que no me parezca increíble tener el mejor trabajo del mundo gracias a las personas que creen en mí.'),
    SEC('Las personas que leen'),
    M('1.743','respuestas recibieron mis correos','Un 89% más que el año pasado.'),
    M('1.330','correos respondidos','414 aún pendientes.'),
    M('58 hs. 17 min.','pasé respondiendo correos','Un 47% más que el año pasado.'),
    M('449','mensajes de recomendación acumulados','108 este año — y cada mensaje es más lindo que el anterior. <a href="https://amor.cflc.email">Leé todos →</a>'),
    M('1.157','suscriptores en mi canal de Telegram','Un 101,5% más. 1.438 en el <a href="https://t.me/comofuncionanlascosas">canal de Cómo funcionan las cosas</a>.'),
    SEC('Club de la curiosidad'),
    M('126 hs. 53 min.','pasé en el Club de la curiosidad','La mitad de los correos tomó más de 12 hs. y un tercio más de 20 hs.'),
    M('28','correos del Club','102 curiosidades · 34 citas · dos diarios de viaje.'),
    M('$94.471','pesos en correo postal','Envío, materiales, impresión y obsequios.'),
    SEC('El dinero'),
    M('$1.890','USD — Mailchimp este año','$4.514,61 total acumulado.'),
    M('$104.595,60','pesos donados en 2021','A Fundación Huésped, Médicos Sin Fronteras, Hacé Feliz a un Gato, Bicho Feliz, Museo del Cine, Internet Archive, The Marginalian, Wikimedia, Parque Podcast, Revista Seúl y muchas otras. <a href="https://docs.google.com/spreadsheets/d/1wEtxpbgtjzo8Fc_quprPtwVvCKGcPIpbpyFSVj-hM1Q/edit?usp=sharing">Ver registro</a>.'),
    M('$39.507','pesos donados en 2022','Parcial a la fecha. Mismas organizaciones y proyectos.'),
    SEC('Redes sociales'),
    M('1.650','nuevos seguidores en Twitter','Un 6% menos que el año pasado.'),
    M('6.553','nuevos seguidores en Instagram','Un 26% menos que el año pasado.'),
    M('14 hs. 43 min.','pasé en diseño y redes sociales','10 horas menos que el año anterior.'),
  ]
},
{
  id:'2022-2023', label:'Años 6 y 7', period:'Abr 2022 — Abr 2024 · La carta de estos dos años se envió en abril de 2024.', color:'#4a8fd1',
  stats:[
    M('14.486','personas que leen',null,true),
    M('55.51%','tasa de apertura','Promedio de 35 correos en los dos años. Un 2% más que en 2021.'),
    M('33.565','personas alguna vez recibieron mis correos','8.194 se desuscribieron. 10.531 archivadas por inactividad.'),
    M('3.828','personas se suscribieron en los dos años'),
    M('2.098','personas se desuscribieron en los dos años'),
    M('40','personas se sumaron cada semana, en promedio','Un 67% menos que en 2021.'),
    M('22','personas se desuscribieron por semana','Un 35% menos que en 2021.'),
    M('255','suscripciones en una semana','El máximo del período, luego de <a href="https://comofuncionanlascos.as/soda-5dc45059f617">"cómo funciona la soda"</a> (oct. 2023).',true),
    M('112','desuscripciones en una semana — máximo del período','Tras el reenvío de <a href="https://comofuncionanlascos.as/hacer-un-regalo-9a39be043f47">"cómo funciona hacer un regalo"</a> (dic. 2023).'),
    M('1.019','temas sugeridos','47 en 2022 · 53 en 2023. "Cómo funciona viajar por el mundo" sigue siendo el más pedido. <a href="https://docs.google.com/forms/d/e/1FAIpQLSd-e8baQbuF1u_qVWJ4F9Bx2Nzy9wEeNXlhIJIVLwN-QoK7Zw/viewform">¿Querés sugerir uno?</a>'),
    M('35','correos distintos','En los dos años. 33 menos que en 2020/2021.'),
    M('507','correos enviados en 7 años','138 distintos "cómo funciona" · 189 extras para el Club · el resto son aventuras literarias, filosóficas y científicas.'),
    M('84 días','fue el máximo que pasé sin enviar correos en 2022.','En 2023 el máximo fue de 83 días.'),
    M('412 hs. 29 min.','pasé investigando y escribiendo','En los dos años. Promedio de 23 hs. 19 min. por "cómo funciona".'),
    M('34 hs. 7 min.','el correo más lento de la historia','<a href="https://comofuncionanlascos.as/soda-5dc45059f617">"Cómo funciona la soda"</a>. Nuevo récord. El más rápido: <a href="https://comofuncionanlascos.as/pasear-un-perro-50089d547fc9">"pasear un perro"</a>, 15 hs. 3 min.',true),
    M('154 libros + 100 artículos','consulté para escribir en los dos años'),
    M('10 hs. 56 min.','pasé grabando y editando lecturas','En los dos años.'),
    M('10 hs. 46 min.','pasé analizando números y escribiendo mi resumen anual de 2022','<i class="up">▲</i> 1 hs. 42 min. más que el año anterior.'),
    M('1','libro publicado','<a href="https://valentinmuro.com/que-preguntas"><em>¿Qué preguntas?</em></a> — 182 hs. 2 min. de trabajo, más 32 hs. 49 min. después de la publicación.'),
    M('0','libros impresos en Argentina','Por decisión de Santillana, que tiene la exclusividad de los derechos.'),
    M('4','exámenes finales aprobados','1 pendiente junto a una tesis para recibirme.'),
    M('1','carrera académica dejé incompleta','Luego de no soportar más el abuso y el maltrato a raíz de presentar mi diagnóstico de autismo en la Facultad.'),
    ST('Junio de 2022 fue el mes con más nuevos apoyos (unas 33 personas). Septiembre de 2022 fue el último mes en que creció el Club. Desde entonces, cada mes cancelan más personas que las que se suman. No hay un solo día en el que no me parezca increíble tener el mejor trabajo del mundo gracias a las personas que creen en mí.'),
    SEC('Las personas que leen'),
    M('1.182','respuestas recibieron mis correos','En los dos años.'),
    M('686','correos respondidos','636 aún pendientes.'),
    M('108 hs. 21 min.','pasé respondiendo correos','9 min. 45 seg. por correo en promedio.'),
    M('528','personas recomendaron mi trabajo','<a href="https://amor.cflc.email">Leé todos en amor.cflc.email →</a>'),
    M('386','ideas para sentirse un poco mejor','En <a href="https://28dias.cflc.email/ideas">este sitio</a> — tomó 26 hs. 46 min.'),
    SEC('Club de la curiosidad'),
    M('110','videollamadas mantuve con personas del Club'),
    M('166 hs. 21 min.','pasé en videollamadas del Club','Promedio de 1 hs. 23 min. por llamada.'),
    M('1 hs. 23 min.','en promedio duró cada videollamada'),
    M('1.988','mensajes en el foro del Club','En <a href="https://foro.curiosidad.club">foro.curiosidad.club</a> — 106 temas · 389 cuentas · 39 participan activamente.'),
    M('28','correos del Club','35 curiosidades · 7 citas · diarios de viaje.'),
    M('34 hs. 24 min.','pasé en correos extras del Club'),
    M('495','correos en el Museo','<a href="https://museo.curiosidad.club">museo.curiosidad.club</a> — restan cargar 12.'),
    SEC('Encuentros de libros'),
    M('6,5','libros leídos y discutidos','1.305 páginas · 25 encuentros por videollamada · 1 recorrido en vivo por Torino mostrando los lugares de Italo Calvino.'),
    M('80 hs. 52 min.','pasé en encuentros de lectura'),
    M('119 hs. 59 min.','pasé haciendo resúmenes, diapositivas y coordinación'),
    SEC('El dinero'),
    M('USD 6.032,73','fue el costo total del período','En los dos años.',true),
    M('USD 2.479,73','invertí en 2022','<span class="s-line">USD 2.381 en Mailchimp.</span><span class="s-line">USD 98,72 en dominios.</span>'),
    M('USD 3.553','invertí en 2023','<span class="s-line">USD 1.540 en Mailchimp.</span><span class="s-line">USD 1.535 en MailerLite.</span><span class="s-line">USD 359,64 en dominios.</span><span class="s-line">USD 90,28 en Foro · USD 27,28 en plantillas.</span>'),
    M('USD 1.015,08','doné en los dos años','A <a href="https://docs.google.com/spreadsheets/d/1wEtxpbgtjzo8Fc_quprPtwVvCKGcPIpbpyFSVj-hM1Q/">33 proyectos e iniciativas</a>.'),
  ]
},
{
  id:'2024', label:'Año 8', period:'Abr 2024 — Abr 2025', color:'#4abf8a',
  stats:[
    M('14.360','personas que leen','126 menos que hace un año.',true),
    M('55.59%','tasa de apertura','0,37% más baja — promedio de 42 correos.'),
    M('35.103','personas alguna vez recibieron mis correos','9.651 se desuscribieron. 10.531 archivadas por inactividad.'),
    M('1.548','personas se suscribieron este año'),
    M('1.460','personas se desuscribieron este año'),
    M('30','personas se sumaron cada semana, en promedio','Un 8% más que el año anterior.'),
    M('28','personas se desuscribieron por semana','Un 23% más que el año anterior.'),
    M('170','suscripciones en una semana','El máximo del año, luego de <a href="https://comofuncionanlascos.as/leer-con-otros-80dd85d3d320">"ideas para leer con otros"</a> (enero).',true),
    M('169','desuscripciones en una semana','El máximo del año, al reenviar <a href="https://comofuncionanlascos.as/voz-interior-2377ad0303e4">"cómo funciona nuestra voz en la cabeza"</a> (septiembre).'),
    M('1.081+','temas sugeridos','57 este año. "Cómo funciona viajar" sigue siendo el más pedido.'),
    M('42','correos enviados','5 más que el año anterior.'),
    M('554','correos enviados en 8 años','149 distintos "cómo funciona" · 189 extras para el Club · el resto son aventuras literarias, filosóficas y científicas.'),
    M('149','temas distintos de "cómo funciona"','11 nuevos este año · 7 reediciones · 2 misceláneas · 1 preguntas de niños · 1 citas apócrifas · 16 para el Club.'),
    M('15','veces marcaron spam'),
    M('49 días','fue el máximo que pasé sin enviar correos.','Un 65% menos que el año anterior.'),
    M('299 hs. 37 min.','pasé investigando y escribiendo','Un 19,45% más que el año anterior.'),
    M('17 hs. 10 min.','en promedio me tomó cada "cómo funciona"','<span class="s-line">El más rápido: <a href="https://comofuncionanlascos.as/despedidas-599bcab7c346">"despedidas"</a> (9 hs. 13 min.).</span><span class="s-line">El más lento: <a href="https://comofuncionanlascos.as/andar-descalzo-3f639855dc00">"andar descalzo"</a> (27 hs. 12 min.).</span>',true),
    M('135 libros + 44 artículos','consulté para escribir este año'),
    M('6 hs. 5 min.','pasé grabando y editando lecturas','Un 40% más que el año anterior.'),
    M('16 hs. 33 min.','pasé analizando números y escribiendo mi resumen anual','<i class="up">▲</i> 5 hs. 47 min. más que la anterior.'),
    M('28 hs. 33 min.','armando los 28 Días','334 personas se sumaron este año. <a href="https://28dias.cflc.email">28dias.cflc.email</a>.'),
    M('1','libro presentado en Buenos Aires','<a href="https://valentinmuro.com/que-preguntas"><em>¿Qué preguntas?</em></a> — <a href="https://www.instagram.com/p/C7IOd2GuGyB/">53 dedicatorias únicas</a> para quienes vinieron a retirarlo en persona.'),
    M('0','libros impresos en Argentina','Por decisión de Santillana.'),
    SEC('Las personas que leen'),
    M('643','respuestas recibieron mis correos','15 por correo en promedio.'),
    M('882','correos respondidos','640 aún pendientes.'),
    M('72 hs. 25 min.','pasé respondiendo correos','4 min. 56 seg. por correo en promedio.'),
    M('574','personas recomendaron mi trabajo','<span class="s-line">44 nuevas este año.</span><span class="s-line"><a href="https://amor.cflc.email">amor.cflc.email →</a></span>'),
    M('337','ideas para sentirse un poco mejor','<a href="https://28dias.cflc.email/ideas">28dias.cflc.email/ideas</a>.'),
    SEC('Club de la curiosidad'),
    M('171','personas se sumaron a apoyarme','186 dejaron de hacerlo — 15 personas menos que el año anterior.'),
    M('73,36%','son mujeres entre quienes apoyan mi trabajo','26,64% varones — <i class="up">▲</i> 0,67% más que el año anterior.'),
    M('59','videollamadas mantuve con personas del Club','Un 10% más que el año anterior.'),
    M('94 hs. 19 min.','pasé en videollamadas del Club','Un 7,45% menos de tiempo que el año anterior.'),
    M('1 hs. 35 min.','en promedio duró cada videollamada'),
    M('840','mensajes en el foro del Club','En 44 nuevos temas. Enero fue el mes con mayor participación.'),
    M('495','correos en el Museo','<a href="https://museo.curiosidad.club">museo.curiosidad.club</a> — restan cargar 58.'),
    M('0','días sin que me parezca increíble','Tener este trabajo gracias a quienes creen en mí.'),
    SEC('Encuentros de libros'),
    M('8','libros leídos y discutidos'),
    M('156 hs. 47 min.','pasé en encuentros de lectura'),
    M('61 hs. 49 min.','pasé haciendo resúmenes, diapositivas y coordinación'),
    SEC('El dinero'),
    M('USD 1.934,12','fue el costo total de este año','<span class="s-line"><i class="dn">▼</i> USD 1.846,49 menos que el año anterior.</span><span class="s-line">USD 13.429,41 invertidos desde el comienzo.</span>',true),
    M('USD 1.600','invertí en MailerLite','<span class="s-line">USD 334,12 en dominios, servidores y herramientas.</span>'),
    M('USD 690,66','doné este año','<span class="s-line"><i class="dn">▼</i> USD 324,42 menos que el año anterior.</span><span class="s-line"><a href="https://docs.google.com/spreadsheets/d/1wEtxpbgtjzo8Fc_quprPtwVvCKGcPIpbpyFSVj-hM1Q/edit?usp=sharing">Ver registro</a>.</span>'),
    M('USD 3.843,82','doné desde 2019'),
  ]
},
{
  id:'2025', label:'Año 9', period:'Abr 2025 — Abr 2026', color:'#44AA99',
  stats:[
    M('13.741','personas que leen','<span class="s-line"><i class="dn">▼</i> 619 menos que hace un año.</span>',true),
    M('52%','tasa de apertura','<span class="s-line"><i class="dn">▼</i> 3,59% menos que el año anterior — promedio de 33 correos.</span>'),
    M('36.142','personas alguna vez recibieron mis correos','10.837 se desuscribieron. 10.531 archivadas por inactividad.'),
    M('1.039','personas se suscribieron este año'),
    M('1.186','personas se desuscribieron este año'),
    M('20','personas se sumaron cada semana, en promedio','<i class="dn">▼</i> Un 33% menos que el año anterior.'),
    M('23','personas se desuscribieron por semana','<i class="dn">▼</i> Un 18% menos que el año anterior.'),
    M('115','suscripciones en una semana','Luego de <em>Una vida en la curiosidad</em> (8 jun. 2025).',true),
    M('144','desuscripciones en una semana','Luego de <em>Cómo funciona la vergüenza</em> (bis) (16 nov. 2025).'),
    M('1.100+','temas sugeridos','53 este año. "Cómo funciona viajar" sigue siendo el más pedido.'),
    M('33','correos CFLC enviados','<span class="s-line"><i class="up">▲</i> 12 más que el año anterior.</span><span class="s-line">+ 17 para el Club · 50 en total.</span>'),
    M('593','correos enviados en 9 años','158 distintos "cómo funciona" · 189 extras para el Club · el resto son aventuras literarias, filosóficas y científicas. <a href="https://museo.curiosidad.club">museo.curiosidad.club</a>.'),
    M('158','temas distintos de "cómo funciona"','<span class="s-line">8 nuevos este año · 8 reediciones (bis).</span><span class="s-line"><i class="up">▲</i> 9 más que el año anterior.</span>'),
    M('13','veces marcaron spam'),
    M('21 días','fue el máximo que pasé sin enviar correos.','<i class="dn">▼</i> Un 57% menos que el año anterior.'),
    M('282 hs.','pasé investigando y escribiendo','<i class="dn">▼</i> Un 5,9% menos que el año anterior.'),
    M('14 hs. 51 min.','en promedio me tomó cada "cómo funciona"','<span class="s-line">El más rápido: <em>Cómo funciona levantarse</em> (4 hs. 42 min.).</span><span class="s-line">El más lento: <em>Cómo funcionan los sándwiches</em> (28 hs. 28 min.).</span>',true),
    M('63 libros + 29 artículos','consulté para escribir este año'),
    M('11 hs. 17 min.','pasé grabando y editando lecturas'),
    M('16 hs. 15 min.','pasé analizando números y escribiendo mi resumen anual','<i class="dn">▼</i> 18 min. menos que la anterior.'),
    SEC('Las personas que leen'),
    M('38','respuestas recibí a la carta del año anterior'),
    M('613','respuestas recibieron mis correos','<span class="s-line">12,3 por correo en promedio.</span><span class="s-line"><i class="dn">▼</i> Un 4,7% menos que el año anterior.</span>'),
    M('667','correos pendientes de responder','Al 18 de abril de 2026.'),
    M('46 hs.','pasé respondiendo correos'),
    M('545','conversaciones mantuve con personas que leen','<span class="s-line"><i class="up">▲</i> Un 2,4% más que el año anterior.</span><span class="s-line">816 mensajes totales · 233 generales · 583 Club.</span>',false,'156 generales · 389 en el Club'),
    M('609','personas recomendaron mi trabajo','<span class="s-line"><i class="up">▲</i> 35 nuevas este año.</span><span class="s-line"><a href="https://amor.cflc.email">amor.cflc.email →</a></span>'),
    SEC('Club de la curiosidad'),
    M('132','personas se sumaron a apoyarme','<span class="s-line"><i class="dn">▼</i> 201 dejaron de hacerlo.</span><span class="s-line">69 personas menos en el Club que hace un año.</span>'),
    M('71,43%','son mujeres entre quienes apoyan mi trabajo','<span class="s-line">28,57% varones — <i class="up">▲</i> 1,93% más que el año anterior.</span>'),
    M('32','videollamadas mantuve con personas del Club','<span class="s-line"><i class="dn">▼</i> Un 43% menos que el año anterior.</span>'),
    M('43 hs.','pasé en videollamadas del Club'),
    M('1 hs. 21 min.','en promedio duró cada videollamada'),
    M('441','mensajes en el foro del Club','<span class="s-line">23 nuevos temas · 84 nuevas cuentas.</span><span class="s-line"><a href="https://foro.curiosidad.club">foro.curiosidad.club</a>.</span>'),
    M('8 hs. 1 min.','pasé en correos extras del Club'),
    M('185 hs.','pasé trabajando en correos y proyectos del Club','<i class="up">▲</i> Un 91% más que el año anterior.'),
    SEC('Encuentros de libros'),
    M('4 libros + 1 selección de poesía','leídos y discutidos'),
    M('66 hs.','pasé en encuentros de lectura','<i class="dn">▼</i> Un 58% menos que el año anterior.'),
    M('22 hs.','pasé haciendo resúmenes, diapositivas y coordinación','<i class="dn">▼</i> Un 64% menos que el año anterior.'),
    SEC('El dinero'),
    M('USD 1.960,88','fue el costo total de este año','<span class="s-line"><i class="up">▲</i> USD 26,76 más que el año anterior.</span><span class="s-line">USD 15.390,29 invertidos desde el comienzo.</span>',true),
    M('USD 1.560','invertí en MailerLite','<span class="s-line">USD 196,80 en Google Workspace.</span><span class="s-line">USD 109,20 en Digital Ocean.</span><span class="s-line">USD 94,88 en dominios.</span>'),
    M('USD 1.051,76','doné este año','<span class="s-line"><i class="up">▲</i> USD 361,10 más que el año anterior.</span><span class="s-line"><a href="https://docs.google.com/spreadsheets/d/1wEtxpbgtjzo8Fc_quprPtwVvCKGcPIpbpyFSVj-hM1Q/edit?usp=sharing">Ver registro</a>.</span>'),
    M('USD 4.709,05','doné desde 2019'),
  ]
}
];
